### ISSUE TITLE
Add a "counter" feature like greenshot

### ISSUE THREAD

**Issue by bbigras** [lupoDharkael/flameshot#275] opened 2018-07-20 14:12 UTC
I use Greenshot on Windows and it's pretty nice to be able to add "counters" to show people the order of the steps, like this:

![image](https://user-images.githubusercontent.com/24027/43006773-94676916-8c04-11e8-9d15-f47c13a9c62b.png)

**Comment by Rmano** [comment] 2018-08-27 13:44
This is a duplicate of https://github.com/lupoDharkael/flameshot/issues/187

**Closed** 2018-08-27 14:16 UTC
