### ISSUE TITLE
dual monitor 

### ISSUE THREAD

**Issue by icf20** [lupoDharkael/flameshot#2] opened 2017-07-02 13:00 UTC
hello atm this only works on the main monitor and secondary monitor is ignored 
1 `flameshot gui`

2 the main monitor gets the notification

3 outside main monitor the cross cursor become normal mouse pointer

**Comment by lupoDharkael** [comment] 2017-07-02 13:05
please, provide more information so I can try to reproduce the bug. What is your distro/system and its version?

**Comment by icf20** [comment] 2017-07-02 13:47
> What is your distro and your desktop environment?

arch and bspwm

**Comment by lupoDharkael** [comment] 2017-07-02 14:23
It seems that the bug is reproducible in Awesomewm. I'll investigate it.

**Comment by karlos1337** [comment] 2017-07-10 07:39
Same in antergos (arch) and cinnamon desktop

**Comment by lupoDharkael** [comment] 2017-07-10 16:12
It seems to be a problem related to geometry and not dependent on specific systems (not at all).
Could you please tell me about your screen resolutions involved in the issue? That could be useful information.

This week I plan to try to solve this with some friends as testers (so hopefully it wont end breaking previously working setups).

**Comment by karlos1337** [comment] 2017-07-10 16:26
I have 3 monitors, from right to left, 1366x768 - 1920x1080 - 1680x1050, the first is the desktop main monitor and the only where flameshot can capture anything.

Thx.

**Comment by lupoDharkael** [comment] 2017-07-12 09:29
I think I've found a solution. I was working on it in an alternative branch and I've merged it because a friend told me it solved the issue. Could you test Flameshot from the master branch and tell me if it works?

**Comment by karlos1337** [comment] 2017-07-12 10:50
@lupoDharkael It works perfectly :)

Thx.

**Comment by lupoDharkael** [comment] 2017-07-12 19:12
please @icf20 tell me if works for you from the master branch.

**Comment by Chryseus** [comment] 2017-07-12 20:11
Can confirm it works.

**Comment by lupoDharkael** [comment] 2017-07-19 12:08
ok, so I'm closing the issue now as it seems to be fixed. I plan to release a new version soon with this fix and a lot of new features!

**Closed** 2017-07-19 12:08 UTC
Labels: bug

**Comment by icf20** [comment] 2017-07-23 22:22
@lupoDharkael  i am still on version  flameshot  0.2.1-3 i will report back after the update hits arch(aur)

**Comment by arunjoys** [comment] 2021-08-23 13:31
I was also facing 

> hello atm this only works on the main monitor and secondary monitor is ignored
> 1 `flameshot gui`
> 
> 2 the main monitor gets the notification
> 
> 3 outside main monitor the cross cursor become normal mouse pointer

I was also facing the issue. I made other monitor as my primary monitor and Issue resolved
