### ISSUE TITLE
Cusrsor is mostly invisible during screenshots

### ISSUE THREAD

**Issue by douglasg14b** [lupoDharkael/flameshot#329] opened 2018-08-29 21:42 UTC
**Flameshot version**
Flameshot 0.5.1-1(Debian)

**Describe the bug**
The selection cursor is the same black color as the black shade over the screen

**To Reproduce**
Take a screenshot.

**Expected behavior**
The cursor to be visible

**System Information**
Ubuntu 18.04
Using Breeze Dark theme

**Comment by lupoDharkael** [comment] 2018-11-13 13:18
duplicate of https://github.com/lupoDharkael/flameshot/issues/82

**Closed** 2018-11-13 13:19 UTC
Labels: duplicate
