### ISSUE TITLE
fatal reproducible system wide crash/freeze when pressing escape

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [lupoDharkael/flameshot#173] opened 2018-03-25 12:19 UTC
Hey devs !

I have some bad news, I appear to have a critical, reproducible bug. Apparently every time I select an area to take a shot, if after drawing the box I press "escape" the system freezes and I can't do anything beside ctrl+alt+delete to restart the gui. I know I had crashes from time to time but this makes it really unusable for me.

I'm on Ubuntu 16.04 and `flameshot --version` returns `Flameshot v0.5.0-51-g248c446 ; Compiled with QT 5.5.1`

What logs should I provide to help resolve this issue ?

**Comment by lupoDharkael** [comment] 2018-03-25 13:55
What's your desktop environment?

**Comment by thiswillbeyourgithub** [comment] 2018-03-25 13:57
Out of the box unity I guess. I have installed other DE to test them and them tried to remove them, so my unity is probably a bit altered but I'd VERY surprised that's the cause.

I have to add that I have had this problem for a while. It's not very recent.

**Comment by lupoDharkael** [comment] 2018-03-25 14:36
Did you update Flameshot right before it started to cause this error? I you didn't that could be caused by other component in the system. 
If Flameshot had this kind of bug it would have been reported before. The Escape shortcut just closes the widget and nothing more. It could be a bug somewhere in the DE, a simple bug in a program shouldn't cause such a serious repercussion in your system just closing a widget.

**Comment by thiswillbeyourgithub** [comment] 2018-03-25 15:25
I don't know about the update.

I guess you're right. I'll try reinstalling it just in case. Do you have any idea what logs I should check if it's my unity install ?

**Comment by lupoDharkael** [comment] 2018-03-25 16:59
I'm sorry but I don't know much about Unity, I've used it a few times just to test Flameshot on Ubuntu :(
I'm closing the issue as I can't reproduce. Just let me know if you find something of interest so I can find if it's a bug in Flameshot.

**Closed by lupoDharkael** 2018-03-25 16:59 UTC

**Comment by thiswillbeyourgithub** [comment] 2018-03-25 17:31
Hum. Sorry for disturbing you again but I was trying to reinstall it and I don't know exactly how I installed flameshot as it was a while ago but I can't seem to be able to remove it first.

Neither `sudo apt(or apt-get) remove flameshot` nor `dpkg -r flameshot` finds it.
`dpkg --list|grep flame` returns nothing and `which flameshot` returns `/usr/local/bin/flameshot`. Do you have any idea what happenned ?

**Comment by lupoDharkael** [comment] 2018-03-25 17:39
You probably did a `make install` after a manual compilation.
If you want to remove the package (in case you installed it with make) you have to generate the makefile without with `qmake` and run `sudo make uninstall`.

**Comment by sidmint** [comment] 2020-11-08 17:10
Same issue here: i select a region and press escape to get a freeze. And it was also there when I tested it 1-2 months ago. I have tried this many times and got the issue many times easily [about one in 10 to 20 times issue comes] but could not get any clue to reproduce it as it is very random. Though it happens more on first launch after log in/restart.

But today I caught it red handed:
![1](https://user-images.githubusercontent.com/43943312/98471555-237c3e00-2213-11eb-95ef-4c10e9699a6c.gif)
here, i pressed escape and then only cursor is moving, i put the cursor over various options and pressed right and left clicks without effect and then i quit by ctrl-alt-backspace.

**Comment by sidmint** [comment] 2020-11-08 22:14
I reproduce it this way in simple steps: press ctrl-alt-backspace, select a region by flameshot, press escape.
If I do above steps repeateadly 10 times, I get the issue usually at least one time. Thats the rough probability of it.

Linuxmint 19.3 xfce 64bit.
