### ISSUE TITLE
Add a delay (Enhancement)

### ISSUE THREAD

**Issue by sterndata** [lupoDharkael/flameshot#233] opened 2018-05-30 13:44 UTC
Thank you for creating this application!

One of the nice things in Shutter, which does not run on Wayland, is that it allows a delay between selecting the target area and taking the screenshot.  This allows one to draw the area, then do something with the mouse like opening a dropdown.  

So, my request is that the configuration support an optional delay between selecting a screenshot aea and grabbing the pixels, during which the user can use their mouse "normally" on the screen.

**Comment by Rmano** [comment] 2018-08-27 13:56
Notice that you can do something like 
```
flameshot screen -d 5000
```
and have a screenshot after 5 seconds delay, or 
```
flameshot gui -d 5000
```
to be able to select the rectangular zone --- although in that case, you choose the zone _after_ the delay expired (which is quite strange). 
Also, a countdown would be nice to have...

**Comment by AlexWayfer** [comment] 2018-09-03 07:05
Duplicate of #124, I guess.

**Closed** 2018-09-03 09:49 UTC

**Comment by mortasoft** [comment] 2019-03-01 21:23
How that can be done in the GUI??

**Comment by cipricus** [comment] 2019-06-22 21:37
> Notice that you can do something like
> 
> ```
> flameshot screen -d 5000
> ```
> 
> and have a screenshot after 5 seconds delay, or
> 
> ```
> flameshot gui -d 5000
> ```
> 
> to be able to select the rectangular zone --- although in that case, you choose the zone _after_ the delay expired (which is quite strange).
> Also, a countdown would be nice to have...
Typing in terminal --

```
flameshot screen -d 5000
'screen' is not a valid argument. See 'flameshot --help'.
```

`flameshot gui -d 5000`, on the other hand, works fine.

**Comment by Mart-Bogdan** [comment] 2019-07-07 20:10
Please reopen this.
This should be available from the context menu of tray icon!

**Comment by luzpaz** [comment] 2019-09-29 15:35
There is no mention of the -d flag at all in the CLI help: (v0.6.0-63-g19d70110)  
```bash
$ flameshot --help
Usage: flameshot [flameshot-options] [arguments]

Options:
  -h, --help     Displays this help
  -v, --version  Displays version information

Arguments:
  gui            Start a manual capture in GUI mode.
  screen         Capture a single screen.
  full           Capture the entire desktop.
  launcher       Open the capture launcher.
  config         Configure flameshot.
```

**Comment by AlexWayfer** [comment] 2019-09-30 11:24
@luzpaz, it's in `gui` sub-command:

```
> flameshot gui --help
Usage: flameshot gui [gui-options] 

Options:
  -p, --path <path>           Path where the capture will be saved
  -d, --delay <milliseconds>  Delay time in milliseconds
  -r, --raw                   Print raw PNG capture
  -h, --help                  Displays this help
```

**Comment by luzpaz** [comment] 2019-09-30 12:44
@AlexWayfer thanks. I think that the top level `--help` flag should list all this subcommand flag. What's the harm ?

**Comment by Mart-Bogdan** [comment] 2019-09-30 13:29
cli flag is good, but having such option from tray icon would be better.
Flameshot is starting with system anyway, and sits in a tray.

**Comment by benwinding** [comment] 2019-10-17 02:14
There's so many buttons around the screen capture selection, how about another one?
![ssss](https://user-images.githubusercontent.com/11782590/66972338-e4e18600-f0db-11e9-8ebd-f6995749fa43.png)

**Comment by mortasoft** [comment] 2019-10-17 02:51
> There's so many buttons around the screen capture selection, how about another one?
> ![ssss](https://user-images.githubusercontent.com/11782590/66972338-e4e18600-f0db-11e9-8ebd-f6995749fa43.png)

Yea I like that. Why there's no delay in the GUI?.
Almost all the screenshot apps had it.

**Comment by AlexWayfer** [comment] 2019-10-17 10:17
Selection size and position can be not obvious before pop-up shows, for example. So, it's better to place delay in something like drop-down menu of top-bar icon.

**Comment by marcosfede** [comment] 2020-01-22 18:08
@AlexWayfer suggestion sounds really good, could you open this issue again?

**Comment by AlexWayfer** [comment] 2020-01-22 18:35
> @AlexWayfer suggestion sounds really good, could you open this issue again?

I'm not a collaborator or author of this issue, so no. Anyway, this issue is a duplicate of #124, how it was mentioned before closing.
